version: "3.9"

x-template-common: &common-service
  restart: always
  logging:
    driver: json-file
  networks:
    - net
    
x-template-client: &client-service
  <<: *common-service
  depends_on:
    - api
  links:
    - "api:api"
    
x-template-wb: &wb-service
  <<: *common-service
  depends_on:
    - websocketserver
  links:
    - "websocketserver:wb"
    
networks:
  net:

services:
  postgres:
    <<: *common-service
    image: postgres
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PAS}
      - POSTGRES_DB=${PG_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./Volumes/start_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    shm_size: 2gb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
  writter:
    <<: *client-service
    container_name: writter
    build:
      context: .
      dockerfile: ./src/testWorkKoshelek.WritterClient/Dockerfile
    environment:
      - ApiOptions__Uri=http://api/id
    ports: 
      - 5183:80
  getter:
    <<: *client-service
    container_name: getter-by-period
    build:
      context: .
      dockerfile: ./src/testWorkKoshelek.GetterClient/Dockerfile
    environment:
      - ApiOptions__Uri=http://api/id
    ports:
      - 5190:80
  websocketserver:
    <<: *common-service
    container_name: websocket-server
    build:
      context: .
      dockerfile: ./src/testWorkKoshelek.WebSocketServer/Dockerfile
    ports:
      - 5000:80
  api:
    <<: *wb-service
    container_name: api
    build:
      context: .
      dockerfile: ./src/testWorkKoshelek.API/Dockerfile
    depends_on:
      - postgres
    links:
      - "postgres:storage"
    environment:
      - DbOptions__ConnectionString=Server=storage;Port=5432;User Id=postgres;Password=postgres;Database=myDb
      - DbOptions__Scheme=${DB_Scheme}
      - DbOptions__CommandTimeOut=${DB_TimeOut}
      - WebSocketOptions__Uri=ws://wb:5000/api
    ports:
      - 5200:80
  reader:
    <<: *wb-service
    container_name: reader
    build:
      context: .
      dockerfile: ./src/testWorkKoshelek.ReaderClient/Dockerfile
    environment:
      - WebSocketOptions__Uri=ws://wb:5000/api
    ports:
      - 5059:80

volumes:
  Volumes: